apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaniko-deploy-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kaniko-deploy-pod
  template:
    metadata:
      labels:
        name: kaniko-deploy-pod
    spec:
      containers:
      - name: kaniko-deploy-pod
        imagePullPolicy: Always
